openapi: 3.0.1
info:
  title: NewWorld
  description: API Definition of NewWorld
  version: 1.0.0
servers:
- url: http://localhost:8290/newWorld
paths:
  /:
    get:
      responses:
        default:
          description: Default response
